import mysql.connector
def create_hyperlink(text, url):
    return f'<a href="{url}" target="_blank">{text}</a>'
mydb = mysql.connector.connect(host="localhost", user="root", password="admin", database="chatbotdb")
cur = mydb.cursor()

s="insert into chatbots(cbid,name,url,description) values(%s,%s,%s,%s)"
chatbots = [
     (1, 'chatgpt', 'openai.com', 'AI chatbot'),
     (2, 'TensorFlow', 'https://www.tensorflow.org/', 'Machine learning framework'),
     (3, 'OpenAI', 'https://openai.com/', 'Artificial intelligence research organization'),
     (4, 'spaCy', 'https://spacy.io/', 'Natural language processing library'),
     (5, 'NLTK (Natural Language Toolkit)', 'https://www.nltk.org/', 'NLP library for Python'),
     (6, 'OpenCV', 'https://opencv.org/', 'Computer vision library'),
     (7, 'PyTorch', 'https://pytorch.org/', 'Deep learning framework with strong support for computer vision tasks'),
     (8, 'Kaldi', 'http://kaldi-asr.org/', 'Toolkit for speech recognition research'),
     (9, 'Mozilla DeepSpeech', 'https://deepspeech.mozilla.org/', 'Open-source speech-to-text engine'),
     (10, 'IBM Watson Health', 'https://www.ibm.com/watson/health', 'AI-powered healthcare solutions'),
     (11, 'DeepMind Health', 'https://deepmind.com/applied/deepmind-health/', 'AI for healthcare research and applications'),
     (12, 'QuantConnect', 'https://www.quantconnect.com/', 'Algorithmic trading platform using AI'),
     (13, 'AlphaSense', 'https://www.alpha-sense.com/', 'AI-powered financial search engine'),
     (14, 'scikit-learn', 'https://scikit-learn.org/', 'Machine learning library for Python'),
     (15, 'IBM Watson', 'https://www.ibm.com/watson', 'AI platform and services'),
     (16, 'Microsoft Azure AI', 'https://azure.microsoft.com/en-us/services/ai/', 'AI services on the Microsoft Azure cloud platform'),
     (17, 'NVIDIA Deep Learning Institute', 'https://www.nvidia.com/en-us/deep-learning-ai/education/', 'Training and certification in AI and deep learning'),
     (18, 'Hugging Face', 'https://huggingface.co/', 'NLP models and tools'),
     (19, 'AllenNLP', 'https://allennlp.org/', 'NLP research library'),
     (20, 'BERT (Bidirectional Encoder Representations from Transformers)', 'https://github.com/google-research/bert', 'Pre-trained NLP model developed by Google'),
     (21, 'Detectron2', 'https://github.com/facebookresearch/detectron2', 'Object detection library by Facebook AI Research'),
     (22, 'YOLO (You Only Look Once)', 'https://pjreddie.com/darknet/yolo/', 'Real-time object detection system'),
     (23, 'CMU Sphinx', 'https://cmusphinx.github.io/', 'Speech recognition toolkit'),
     (24, 'Wit.ai', 'https://wit.ai/', 'Natural language understanding for developers'),
     (25, 'NVIDIA Clara', 'https://www.nvidia.com/en-us/clara/', 'Healthcare-focused AI platform'),
     (26, 'PathAI', 'https://www.pathai.com/', 'AI-powered pathology solutions'),
     (27, 'Kensho Technologies', 'https://www.kensho.com/', 'AI analytics for financial markets'),
     (28, 'Quantitative Brokers', 'https://quantitativebrokers.com/', 'AI-driven execution algorithms for trading'),
     (29, 'Coursera', 'https://www.coursera.org/', 'Online courses in AI and other subjects'),
     (30, 'Duolingo', 'https://www.duolingo.com/', 'AI-powered language learning platform'),
     (31, 'Salesforce Einstein', 'https://www.salesforce.com/products/einstein/overview/', 'AI for marketing automation and analytics'),
     (32, 'HubSpot Marketing Hub', 'https://www.hubspot.com/products/marketing', 'AI-powered marketing software'),
     (33, 'Fast.ai', 'https://www.fast.ai/', 'Practical deep learning for coders'),
     (34, 'Google AI', 'https://ai.google/', 'Google AI research and projects'),
     (35, 'Amazon AI', 'https://aws.amazon.com/amazon-ai/', 'Amazon AI services and resources'),
     (36, 'The AI Podcast', 'https://blogs.nvidia.com/ai-podcast/', 'Podcast featuring AI experts and researchers'),
     (37, 'OpenAI GPT', 'https://openai.com/gpt/', 'Generative Pre-trained Transformer models by OpenAI'),
     (38, 'Papers with Code', 'https://paperswithcode.com/', 'Free resource with code implementations of AI research papers'),
     (39, 'fastText', 'https://fasttext.cc/', 'Library for efficient text classification and representation learning'),
     (40, 'Microsoft Cognitive Toolkit', 'https://www.microsoft.com/en-us/cognitive-toolkit/', 'Deep learning framework by Microsoft'),
     (41, 'Amazon SageMaker', 'https://aws.amazon.com/sagemaker/', 'Managed service for building, training, and deploying machine learning models'),
     (42, 'The Stanford NLP Group', 'https://nlp.stanford.edu/', 'Natural language processing research at Stanford University'),
     (43, 'OpenAI Gym', 'https://gym.openai.com/', 'Toolkit for developing and comparing reinforcement learning algorithms'),
     (44, 'FastAI Course', 'https://course.fast.ai/', 'Practical deep learning course by FastAI'),
     (45, 'Google Cloud AI', 'https://cloud.google.com/ai/', 'AI solutions and products on Google Cloud Platform'),
     (46, 'Amazon Rekognition', 'https://aws.amazon.com/rekognition/', 'Deep learning-based Photo and video analysis service by Amazon'),
     (47, 'Keras', 'https://keras.io/', 'Deep learning library for Python'),
     (48, 'MIT Deep Learning', 'http://introtodeeplearning.com/', 'Deep learning course materials by MIT'),
     (49, 'DeepMind', 'https://deepmind.com/', 'AI research lab acquired by Google'),
     (50, 'Google Colab', 'https://colab.research.google.com/', 'Free Jupyter notebook environment that runs in the cloud'),
     (51, 'Baidu Research', 'http://research.baidu.com/', 'AI research division of Baidu'),
     (52, 'Facebook AI Research', 'https://ai.facebook.com/research/', 'AI research organization at Facebook'),
     (53, 'Xilinx AI', 'https://www.xilinx.com/ai.html', 'AI solutions and products by Xilinx'),
     (54, 'IBM Research AI', 'https://www.research.ibm.com/artificial-intelligence/', 'AI research initiatives at IBM'),
     (55, 'Deep Learning Indaba', 'https://deeplearningindaba.com/', 'Annual conference on machine learning and AI in Africa'),
(56, 'PyImageSearch', 'https://www.pyimagesearch.com/', 'Tutorials on computer vision and deep learning'),
(57, 'Analytics Vidhya', 'https://www.analyticsvidhya.com/', 'Community for analytics and data science professionals'),
(58, 'KDnuggets', 'https://www.kdnuggets.com/', 'Data science and machine learning news'),
(59, 'ArXiv', 'https://arxiv.org/', 'Open access repository for scientific papers'),
(60, 'SpringerLink', 'https://link.springer.com/', 'Research articles and journals on AI and machine learning'),
(61, 'IEEE Xplore', 'https://ieeexplore.ieee.org/', 'Digital library for IEEE journals and conferences'),
(62, 'Machine Learning Mastery', 'https://machinelearningmastery.com/', 'Resources and tutorials for machine learning practitioners'),
(63, 'Algorithmia', 'https://algorithmia.com/', 'Marketplace for algorithms and AI models'),
(64, 'DeepAI', 'https://deepai.org/', 'AI-powered image recognition and generation tools'),
(65, 'Paperspace', 'https://www.paperspace.com/', 'Cloud-based machine learning platform'),
(66, 'Peltarion', 'https://peltarion.com/', 'AI platform for building and deploying models'),
(67, 'Arthur AI', 'https://www.arthur.ai/', 'AI-powered analytics for data teams'),
(68, 'DataRobot', 'https://www.datarobot.com/', 'Automated machine learning platform'),
(69, 'Intelligent Automation', 'https://www.intelligent-automation.com/', 'AI and automation solutions for enterprises'),
(70, 'TorchCraft AI', 'https://torchcraft.github.io/', 'Framework for AI research in real-time strategy games'),
(71, 'DeepMind StarCraft II', 'https://deepmind.com/research/case-studies/alphastar-mastering-real-time-strategy-game-starcraft-ii', 'Research on AI in StarCraft II game'),
(72, 'Salesforce Research', 'https://www.salesforce.com/research/', 'Research publications and projects from Salesforce'),
(73, 'Google Research', 'https://research.google/', 'Research publications and projects from Google'),
(74, 'Apple Machine Learning Journal', 'https://machinelearning.apple.com/', 'Research articles on machine learning from Apple'),
(75, 'MIT CSAIL', 'https://www.csail.mit.edu/', 'Research laboratory at MIT focusing on AI and computer science'),
(76, 'Allen Institute for AI', 'https://allenai.org/', 'Research institute focused on AI'),
(77, 'Facebook Research', 'https://research.fb.com/', 'Research publications and projects from Facebook'),
(78, 'OpenAI Blog', 'https://openai.com/blog/', 'Blog featuring AI research and projects from OpenAI'),
(79, 'Microsoft Research', 'https://www.microsoft.com/en-us/research/', 'Research publications and projects from Microsoft'),
(80, 'Uber AI', 'https://www.uber.com/us/en/uberai/', 'Research publications and projects from Uber AI'),
(81, 'Samsung AI Center', 'https://www.samsung.com/semiconductor/ai/', 'Research publications and projects from Samsung AI'),
(82, 'NVIDIA AI Research', 'https://www.nvidia.com/en-us/research/', 'Research publications and projects from NVIDIA AI'),
(83, 'DeepMind Research Publications', 'https://deepmind.com/research/publications', 'Research publications from DeepMind'),
(84, 'Google AI Publications', 'https://ai.google/research/pubs', 'Research publications from Google AI'),
(85, 'Facebook AI Research Publications', 'https://research.fb.com/publications/', 'Research publications from Facebook AI Research'),
(86, 'Microsoft Research Publications', 'https://www.microsoft.com/en-us/research/publications/', 'Research publications from Microsoft Research'),
(87, 'MIT CSAIL Publications', 'https://www.csail.mit.edu/publications', 'Research publications from MIT CSAIL'),
(88, 'Allen Institute for AI Publications', 'https://allenai.org/publications/', 'Research publications from Allen Institute for AI'),
(89, 'Uber AI Publications', 'https://www.uber.com/us/en/uberai/publications/', 'Research publications from Uber AI'),
(90, 'Samsung AI Center Publications', 'https://www.samsung.com/semiconductor/ai/publications/', 'Research publications from Samsung AI Center'),
(91, 'NVIDIA AI Research Publications', 'https://www.nvidia.com/en-us/research/publications/', 'Research publications from NVIDIA AI Research'),
(92, 'DeepMind Blog', 'https://deepmind.com/blog', 'Blog featuring AI research and projects from DeepMind'),
(93, 'Google AI Blog', 'https://ai.googleblog.com/', 'Blog featuring AI research and projects from Google AI'),
(94, 'Facebook AI Research Blog', 'https://research.fb.com/blog/', 'Blog featuring AI research and projects from Facebook AI Research'),
(95, 'Microsoft Research Blog', 'https://www.microsoft.com/en-us/research/blog/', 'Blog featuring AI research and projects from Microsoft Research'),
(96, 'Uber AI Blog', 'https://www.uber.com/us/en/uberai/blog/', 'Blog featuring AI research and projects from Uber AI'),
(97, 'Samsung AI Center Blog', 'https://www.samsung.com/semiconductor/ai/blog/', 'Blog featuring AI research and projects from Samsung AI Center'),
(98, 'NVIDIA AI Research Blog', 'https://blogs.nvidia.com/ai/', 'Blog featuring AI research and projects from NVIDIA AI Research'),
(99, 'Baidu Research Blog', 'https://research.baidu.com/Blog', 'Blog featuring AI research and projects from Baidu Research'),
(100, 'Xilinx AI Blog', 'https://www.xilinx.com/ai/blog.html', 'Blog featuring AI research and projects from Xilinx AI'),
(101, 'IBM Research AI Blog', 'https://www.ibm.com/blogs/research/category/ai/', 'Blog featuring AI research and projects from IBM Research AI'),
(102, 'Deep Learning Weekly Newsletter', 'https://www.deeplearningweekly.com/', 'Weekly newsletter on deep learning and AI research'),
(103, 'AI Trends', 'https://www.aitrends.com/', 'Trends and insights on AI and machine learning'),
(104, 'AIXD', 'https://www.aixd.org/', 'Association for the Interaction of Artificial Intelligence and Design'),
(105, 'AI Alignment Forum', 'https://www.alignmentforum.org/', 'Forum discussing AI alignment and safety'),
(106, 'Artificial General Intelligence Society', 'https://www.agi-society.org/', 'Society focused on artificial general intelligence research'),
(107, 'Future of Life Institute', 'https://futureoflife.org/', 'Research and advocacy on existential risks of AI'),
(108, 'AI Impacts', 'https://aiimpacts.org/', 'Research on long-term impacts of AI'),
(109, 'OpenAI LP', 'https://openai.com/', 'AI research and development company'),
(110, 'DeepMind Ethics & Society', 'https://deepmind.com/applied/deepmind-ethics-society/', 'Ethical considerations in AI research and development'),
(111, 'Ethical AI', 'https://ethical.ai/', 'Resources and discussions on ethical AI'),
(112, 'AI Ethics Lab', 'https://aiethicslab.com/', 'Research and education on AI ethics'),
(113, 'Partnership on AI', 'https://www.partnershiponai.org/', 'Collaboration on AI best practices and ethics'),
(114, 'AI Now Institute', 'https://ainowinstitute.org/', 'Research institute focused on societal implications of AI'),
(115, 'Data Science Central', 'https://www.datasciencecentral.com/', 'Community for data science and AI professionals'),
(116, 'Towards Data Science', 'https://towardsdatascience.com/', 'Medium publication on data science and machine learning'),
(117, 'KDnuggets', 'https://www.kdnuggets.com/', 'Data science and machine learning news'),
(118, 'R-bloggers', 'https://www.r-bloggers.com/', 'Blogs on R programming and data science'),
(119, 'Kaggle', 'https://www.kaggle.com/', 'Platform for data science competitions and datasets'),
(120, 'UCI Machine Learning Repository', 'https://archive.ics.uci.edu/ml/index.php', 'Repository of machine learning datasets'),
(121, 'Awesome Public Datasets', 'https://github.com/awesomedata/awesome-public-datasets', 'Curated list of public datasets for machine learning'),
(122, 'Google Dataset Search', 'https://datasetsearch.research.google.com/', 'Search engine for datasets'),
(123, 'Paperspace Gradient', 'https://www.paperspace.com/gradient', 'Platform for machine learning development and deployment'),
(124, 'Weights & Biases', 'https://wandb.ai/', 'Experiment tracking and visualization for machine learning'),
(125, 'Comet.ml', 'https://www.comet.ml/', 'Experiment management platform for machine learning'),
(126, 'Neptune.ai', 'https://neptune.ai/', 'Experiment tracking and collaboration for machine learning'),
(127, 'Dataiku', 'https://www.dataiku.com/', 'Platform for collaborative data science'),
(128, 'Databricks', 'https://databricks.com/', 'Unified analytics platform for big data and machine learning'),
(129, 'Domino Data Lab', 'https://www.dominodatalab.com/', 'Platform for collaborative data science and ML model management'),
(130, 'SAS AI and Machine Learning', 'https://www.sas.com/en_us/software/machine-learning.html', 'AI and machine learning solutions by SAS'),
(131, 'Oracle AI and Machine Learning', 'https://www.oracle.com/ai-and-machine-learning/', 'AI and machine learning solutions by Oracle'),
(132, 'MathWorks MATLAB', 'https://www.mathworks.com/solutions/deep-learning.html', 'Deep learning tools and libraries in MATLAB'),
(133, 'MATLAB Central', 'https://www.mathworks.com/matlabcentral/', 'Community and file exchange for MATLAB users'),
(134, 'MATLAB File Exchange', 'https://www.mathworks.com/matlabcentral/fileexchange/', 'Centralized repository for MATLAB files and toolboxes'),
(135, 'RapidMiner', 'https://rapidminer.com/', 'Data science and machine learning platform'),
(136, 'TIBCO Spotfire', 'https://www.tibco.com/products/data-science/tibco-spotfire', 'Data visualization and analytics platform'),
(137, 'Alteryx', 'https://www.alteryx.com/', 'Data science and analytics platform'),
(138, 'Alteryx Community', 'https://community.alteryx.com/', 'Community for Alteryx users'),
(139, 'KNIME', 'https://www.knime.com/', 'Open-source data analytics platform'),
(140, 'KNIME Hub', 'https://hub.knime.com/', 'Community hub for KNIME workflows and extensions'),
(141, 'Anaconda', 'https://www.anaconda.com/', 'Python distribution for data science and machine learning'),
(142, 'PyPI (Python Package Index)', 'https://pypi.org/', 'Repository for Python packages'),
(143, 'Conda', 'https://conda.io/', 'Package manager for Python'),
(144, 'Scrapy', 'https://scrapy.org/', 'Web crawling and scraping framework in Python'),
(145, 'Beautiful Soup', 'https://www.crummy.com/software/BeautifulSoup/', 'Library for parsing HTML and XML documents'),
(146, 'NLTK (Natural Language Toolkit)', 'https://www.nltk.org/', 'NLP library for Python'),
(147, 'Gensim', 'https://radimrehurek.com/gensim/', 'Topic modeling and document similarity library in Python'),
(148, 'SpaCy', 'https://spacy.io/', 'NLP library for Python'),
(149, 'Transformers by Hugging Face', 'https://huggingface.co/transformers/', 'State-of-the-art NLP models and tools'),
(150, 'NLTK Book', 'https://www.nltk.org/book/', 'Comprehensive guide to NLTK'),
(151, 'Stanford NLP', 'https://nlp.stanford.edu/', 'Natural language processing tools and resources from Stanford University'),
(152, 'Stanford CoreNLP', 'https://stanfordnlp.github.io/CoreNLP/', 'Natural language processing toolkit from Stanford NLP Group'),
(153, 'AllenNLP', 'https://allennlp.org/', 'Deep learning library for NLP tasks'),
(154, 'BERT (Bidirectional Encoder Representations from Transformers)', 'https://github.com/google-research/bert', 'Pre-trained NLP model developed by Google'),
(155, 'GPT (Generative Pre-trained Transformer)', 'https://openai.com/gpt/', 'Pre-trained NLP model developed by OpenAI'),
(156, 'Word2Vec', 'https://code.google.com/archive/p/word2vec/', 'Pre-trained word embeddings by Google'),
(157, 'FastText', 'https://fasttext.cc/', 'Library for efficient text classification and representation learning'),
(158, 'Tesseract OCR', 'https://github.com/tesseract-ocr/', 'Open-source OCR engine by Google'),
(159, 'OpenCV', 'https://opencv.org/', 'Computer vision library'),
(160, 'YOLO (You Only Look Once)', 'https://pjreddie.com/darknet/yolo/', 'Real-time object detection system'),
(161, 'PyTorch', 'https://pytorch.org/', 'Deep learning framework by Facebook AI Research'),
(162, 'Keras', 'https://keras.io/', 'Deep learning library for Python'),
(163, 'Caffe', 'http://caffe.berkeleyvision.org/', 'Deep learning framework developed by Berkeley AI Research'),
(164, 'Torch', 'https://pytorch.org/', 'Deep learning framework by Facebook AI Research'),
(165, 'MXNet', 'https://mxnet.apache.org/', 'Deep learning framework by Apache Software Foundation'),
(166, 'Caffe2', 'https://caffe2.ai/', 'Deep learning framework by Facebook AI Research'),
(167, 'Gluon', 'https://mxnet.apache.org/versions/1.8.0/get_started/get_started.html', 'Deep learning library in Python'),
(168, 'TensorFlow.js', 'https://www.tensorflow.org/js', 'Deep learning in the browser and Node.js'),
(169, 'TensorFlow Lite', 'https://www.tensorflow.org/lite', 'Lightweight deep learning framework for mobile and embedded devices'),
(170, 'ONNX (Open Neural Network Exchange)', 'https://onnx.ai/', 'Open format for representing deep learning models'),
(171, 'DeepDream', 'https://deepdreamgenerator.com/', 'Artistic image generation using deep learning'),
(172, 'DeepArt', 'https://deepart.io/', 'Artistic style transfer using deep neural networks'),
(173, 'DeepStyle', 'https://deepstyle.io/', 'Artistic image generation and style transfer'),
(174, 'DeepAI', 'https://deepai.org/', 'AI-powered image recognition and generation tools'),
(175, 'DeepArtEffects', 'https://deeparteffects.com/', 'Artistic effects and style transfer using AI'),
(176, 'DeepAngel', 'https://deepangel.withgoogle.com/', 'Automatically remove objects from images using AI'),
(177, 'DeepNostalgia', 'https://www.myheritage.com/deep-nostalgia', 'Animate old photos using AI'),
(178, 'DeepFaceLab', 'https://github.com/iperov/DeepFaceLab', 'Facial reenactment and manipulation using AI'),
(179, 'DeepFake', 'https://en.wikipedia.org/wiki/Deepfake', 'Artificially created media in which a person in an existing image or video is replaced with someone else, create fake video'),
(180, 'Hugging Face', 'https://huggingface.co/', 'State-of-the-art NLP models and tools'),
(181, 'Hugging Face Transformers', 'https://huggingface.co/transformers/', 'State-of-the-art NLP models and tools'),
(182, 'Hugging Face Datasets', 'https://huggingface.co/datasets/', 'Datasets for NLP tasks'),
(183, 'Hugging Face Model Hub', 'https://huggingface.co/models', 'Hub for pretrained models'),
(184, 'Fast.ai', 'https://www.fast.ai/', 'Practical deep learning for coders'),
(185, 'FastAI Course', 'https://course.fast.ai/', 'Practical deep learning course by FastAI'),
(186, 'FastBook', 'https://github.com/fastai/fastbook', 'Book on deep learning with FastAI'),
(187, 'FastAI Documentation', 'https://docs.fast.ai/', 'Documentation for FastAI library'),
(188, 'FastAI Forums', 'https://forums.fast.ai/', 'Community forums for FastAI users'),
(189, 'FastAI GitHub Repository', 'https://github.com/fastai/fastai', 'GitHub repository for FastAI library'),
(190, 'FastAI Blog', 'https://www.fast.ai/blog/', 'Blog featuring deep learning projects and tutorials'),
(191, 'FastAI Papers', 'https://www.fast.ai/papers/', 'Papers related to FastAI library'),
(192, 'FastAI Courses', 'https://www.fast.ai/courses/', 'Deep learning courses by FastAI'),
(193, 'FastAI Research', 'https://www.fast.ai/research/', 'Research projects using FastAI library'),
(194, 'FastAI GitHub Organization', 'https://github.com/fastai', 'GitHub organization for FastAI projects'),
(195, 'FastAI Community', 'https://www.fast.ai/community/', 'Community resources for FastAI users'),
(196, 'FastAI Blog Posts', 'https://www.fast.ai/posts/', 'Blog posts on deep learning and FastAI library'),
(197, 'FastAI Lessons', 'https://www.fast.ai/2020/02/13/fastai-A-Lesson/', 'Deep learning lessons by FastAI'),
(198, 'FastAI Resources', 'https://www.fast.ai/resources/', 'Resources for learning deep learning with FastAI'),
(199, 'FastAI Library', 'https://www.fast.ai/library/', 'Library for deep learning with FastAI'),
(200, 'FastAI Examples', 'https://www.fast.ai/examples/', 'Examples of deep learning projects with FastAI'),
(201, 'FastAI YouTube Channel', 'https://www.youtube.com/c/fastdotai', 'YouTube channel for FastAI tutorials and lectures'),
(202, 'FastAI v3', 'https://course.fast.ai/', 'Third version of FastAI deep learning course'),
(203, 'FastAI Swift', 'https://github.com/fastai/swiftai', 'Deep learning library in Swift by FastAI'),
(204, 'FastAI Papers with Code', 'https://paperswithcode.com/lib/fastai', 'Papers with code implementations using FastAI'),
(205, 'FastAI Book', 'https://github.com/fastai/fastbook', 'Book on deep learning with FastAI'),
(206, 'FastAI Community Resources', 'https://forums.fast.ai/t/fastai-community-resources/78892', 'Community resources for FastAI users'),
(207, 'FastAI Research Papers', 'https://forums.fast.ai/t/deep-learning-research-papers/6954', 'Research papers on deep learning and'),
 (208, 'Film Finder', 'https://filmfinder.ai/', 'Find film depeding on your Genre Choice')

      
]

cur.execute("ALTER TABLE chatbots ADD FULLTEXT(name, description)")

hyperlinked_chatbots = []
for chatbot in chatbots:
    name, url, description = chatbot[1], chatbot[2], chatbot[3]
    hyperlinked_url = create_hyperlink(url, url)
    hyperlinked_chatbots.append((chatbot[0], name, hyperlinked_url, description))

cur.executemany(s,chatbots)
mydb.commit()



